[tool.poetry]
name = "text-generation"
version = "0.1.0"
description = ""
authors = ["Harshad Bhandwaldar"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
transformers = "^4.22.2"
torchvision = "^0.13.1"
setuptools = "^65.6.3"


[tool.poetry.group.dev.dependencies]
black = {extras = ["d"], version = "^22.8.0"}
isort = "^5.10.1"
flake8 = "^5.0.4"
mypy = "^0.982"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
# unfortunately cannot inject dependencies into super-linter
# so we have to ignore the imports as they will not have typehints
ignore_missing_imports = true

warn_unused_configs = true
disallow_any_generics = true
# disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
# disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[tool.black]
preview= true
