apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audio-speech-to-text-silero
  namespace: apps
spec:
  secretName: audio-speech-to-text-silero-production-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - audio-speech-to-text-silero.ai-sandbox.4th-ir.io

