apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-speech-to-text-silero
spec:
  progressDeadlineSeconds: 2400
  selector:
    matchLabels:
      app: audio-speech-to-text-silero
  template:
    metadata:
      labels:
        app: audio-speech-to-text-silero
    spec:
      containers:
      - name: audio-speech-to-text-silero
        image: airestservices.azurecr.io/audio_speech_to_text_silero
        ports:
        - containerPort: 8000
      tolerations:
        - key: taintcpu1
          operator: Equal
          value: cpu1
          effect: NoSchedule

