apiVersion: v1
kind: Service
metadata:
  name: image-classification-vissl-svc
spec:
  selector:
    app: image-classification-vissl
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
